/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Magic;

/**
 *
 * @author indra
 */
public class Magic extends javax.swing.JFrame {

    /**
     * Creates new form Magic
     */
    public Magic() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ExitButton = new javax.swing.JButton();
        AmorButton = new javax.swing.JButton();
        WorkButton = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        resultPhraseLabel = new javax.swing.JLabel();
        BackgroundMagic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(0, 0, 204));
        ExitButton.setText("Salir");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 100, 40));

        AmorButton.setBackground(new java.awt.Color(255, 255, 255));
        AmorButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        AmorButton.setForeground(new java.awt.Color(255, 0, 204));
        AmorButton.setText("Amor");
        AmorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AmorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 120, 40));

        WorkButton.setBackground(new java.awt.Color(255, 255, 255));
        WorkButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WorkButton.setForeground(new java.awt.Color(51, 204, 0));
        WorkButton.setText("Trabajo");
        WorkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkButtonActionPerformed(evt);
            }
        });
        jPanel1.add(WorkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 120, 40));

        TitleLabel.setFont(new java.awt.Font("PilGi", 1, 48)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setText("Bola Mágica");
        jPanel1.add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        resultPhraseLabel.setFont(new java.awt.Font("PilGi", 0, 18)); // NOI18N
        resultPhraseLabel.setForeground(new java.awt.Color(255, 51, 51));
        resultPhraseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(resultPhraseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 280, 60));

        BackgroundMagic.setIcon(new javax.swing.ImageIcon("/Users/indra/Desktop/bolaMagica.jpeg")); // NOI18N
        jPanel1.add(BackgroundMagic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AmorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmorButtonActionPerformed
       
        
        Amor love = new Amor();
        love.start();
        try{
        love.join();
        resultPhraseLabel.setText(String.valueOf(love.phrase));
        }
        catch(InterruptedException ex){
            System.out.println("Error: " + ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_AmorButtonActionPerformed

    private void WorkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkButtonActionPerformed
        
        
        Trabajo work = new Trabajo();
        work.start();
        try{
        work.join();
        resultPhraseLabel.setText(String.valueOf(work.phrase));

        }
        catch(InterruptedException ex){
            System.out.println("Error: " + ex.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_WorkButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Magic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Magic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Magic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Magic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Magic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AmorButton;
    private javax.swing.JLabel BackgroundMagic;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton WorkButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultPhraseLabel;
    // End of variables declaration//GEN-END:variables
}
