/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscador;

/**
 *
 * @author indra
 */
public class BuscadorPalabras extends javax.swing.JFrame {

    public static String palabra ="";

    
    /**
     * Creates new form BuscadorPalabras
     */
    public BuscadorPalabras() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscadorBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        palabraInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textResult = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscadorBtn.setIcon(new javax.swing.ImageIcon("/Users/indra/Desktop/lupa.jpeg")); // NOI18N
        buscadorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorBtnActionPerformed(evt);
            }
        });
        getContentPane().add(buscadorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 100, 70));

        jLabel2.setFont(new java.awt.Font("Maku", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        palabraInput.setFont(new java.awt.Font("Maku", 0, 24)); // NOI18N
        palabraInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraInputActionPerformed(evt);
            }
        });
        getContentPane().add(palabraInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 290, 70));

        jLabel1.setFont(new java.awt.Font("Maku", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resultado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        textResult.setColumns(20);
        textResult.setRows(5);
        jScrollPane1.setViewportView(textResult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 390, 150));

        fondo.setFont(new java.awt.Font("Maku", 0, 24)); // NOI18N
        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon("/Users/indra/Desktop/fondo.jpeg")); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 590, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palabraInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palabraInputActionPerformed

    private void buscadorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorBtnActionPerformed

        palabra = palabraInput.getText();

      

      Hilo h1 = new Hilo(palabra, "./Resources/diplomadouscador.txt",textResult);
        Hilo h2 = new Hilo(palabra, "./Resources/diplomadouscador.txt",textResult);
        Hilo h3 = new Hilo(palabra,"./Resources/diplomadouscador.txt",textResult);
        Hilo h4 = new Hilo(palabra,"./Resources/diplomadouscador.txt",textResult);
        Hilo h5 = new Hilo(palabra,"./Resources/diplomadouscador.txt",textResult);
        
       
        
        
        h1.start();
        h2.start();
        h3.start();
        h4.start();
        h5.start();
        
       

    }//GEN-LAST:event_buscadorBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscadorPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscadorPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscadorPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscadorPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscadorPalabras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscadorBtn;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField palabraInput;
    private javax.swing.JTextArea textResult;
    // End of variables declaration//GEN-END:variables
}
