/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author indra
 */
public class Calculadora extends javax.swing.JFrame {
    
       int      one = 0;
       int      two = 0;
       boolean  validate1 = false;
       boolean  validate2 = false;

      
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        
        initComponents();
        this.setLocationRelativeTo(null);

    }

     public boolean validate(String number){
        int n;
        
        try{
        
            n = Integer.parseInt(number);
            return true;
        
        }
        catch(Exception ex){
            
            System.out.println("Error: "+ ex.getMessage());
            return false;
        }
        
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloCalc = new javax.swing.JLabel();
        MultiplicacionLabel = new javax.swing.JLabel();
        NumberoUnoLabel = new javax.swing.JLabel();
        NumeroDosLabel = new javax.swing.JLabel();
        EndButton = new javax.swing.JButton();
        SumaLabel1 = new javax.swing.JLabel();
        RestaLabel1 = new javax.swing.JLabel();
        StartButton1 = new javax.swing.JButton();
        inputTwo = new javax.swing.JTextField();
        inputOne = new javax.swing.JTextField();
        resultMulti = new javax.swing.JLabel();
        resultSuma = new javax.swing.JLabel();
        resultResta = new javax.swing.JLabel();
        BackgroundCalcu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloCalc.setBackground(new java.awt.Color(255, 204, 51));
        TituloCalc.setFont(new java.awt.Font("Silom", 0, 36)); // NOI18N
        TituloCalc.setText("Calculadora");
        jPanel1.add(TituloCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        MultiplicacionLabel.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        MultiplicacionLabel.setText("Multiplicación:");
        jPanel1.add(MultiplicacionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        NumberoUnoLabel.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        NumberoUnoLabel.setText("Número Uno:");
        jPanel1.add(NumberoUnoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        NumeroDosLabel.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        NumeroDosLabel.setText("Número Dos:");
        jPanel1.add(NumeroDosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        EndButton.setBackground(new java.awt.Color(255, 204, 204));
        EndButton.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        EndButton.setForeground(new java.awt.Color(0, 102, 204));
        EndButton.setText("Fin");
        EndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EndButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        SumaLabel1.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        SumaLabel1.setText("Suma:");
        jPanel1.add(SumaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        RestaLabel1.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        RestaLabel1.setText("Resta:");
        jPanel1.add(RestaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 20));

        StartButton1.setBackground(new java.awt.Color(255, 204, 204));
        StartButton1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        StartButton1.setForeground(new java.awt.Color(255, 153, 153));
        StartButton1.setText("Inicio");
        StartButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(StartButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));
        jPanel1.add(inputTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 120, -1));
        jPanel1.add(inputOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 120, -1));

        resultMulti.setText("...");
        jPanel1.add(resultMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        resultSuma.setText("...");
        jPanel1.add(resultSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        resultResta.setText("...");
        jPanel1.add(resultResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        BackgroundCalcu.setIcon(new javax.swing.ImageIcon("/Users/indra/Desktop/fondoCalculadora.jpeg")); // NOI18N
        jPanel1.add(BackgroundCalcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -30, 630, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndButtonActionPerformed
        System.exit(0); //Detiene nuestro proceso y se cierra interfaz
    }//GEN-LAST:event_EndButtonActionPerformed

    private void StartButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButton1ActionPerformed
        
      
        
        validate1 = validate(inputOne.getText());
        validate2 = validate(inputTwo.getText());
        
        if( validate1 == true && validate2 == true ){
        
        one = Integer.parseInt( inputOne.getText() );
        two = Integer.parseInt( inputTwo.getText() );    
            
        Suma  sum = new Suma(one, two);
        Resta res = new Resta(one, two);
        Multi mul = new Multi(one, two);
        
        sum.start();
        res.start();
        mul.start();
        
        try{
            sum.join();
            res.join();
            mul.join();
            
        }catch(InterruptedException ex){
            System.out.println("Error: "+ ex.getMessage());
        }
        
       resultSuma.setText(String.valueOf(sum.r));
       resultResta.setText(String.valueOf(res.r));
       resultMulti.setText(String.valueOf(mul.r));
        }
        else {
            
            JOptionPane.showMessageDialog(rootPane, "Ingrese NÚMEROS");

        }
    }//GEN-LAST:event_StartButton1ActionPerformed
       
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundCalcu;
    private javax.swing.JButton EndButton;
    private javax.swing.JLabel MultiplicacionLabel;
    private javax.swing.JLabel NumberoUnoLabel;
    private javax.swing.JLabel NumeroDosLabel;
    private javax.swing.JLabel RestaLabel1;
    private javax.swing.JButton StartButton1;
    private javax.swing.JLabel SumaLabel1;
    private javax.swing.JLabel TituloCalc;
    private javax.swing.JTextField inputOne;
    private javax.swing.JTextField inputTwo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultMulti;
    private javax.swing.JLabel resultResta;
    private javax.swing.JLabel resultSuma;
    // End of variables declaration//GEN-END:variables

   
}
