/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canicas;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author indra
 */
public class canicas extends javax.swing.JFrame implements Observer{
    
    Izquierda izq = new Izquierda();
    Derecha der = new Derecha();
        
    /**
     * Creates new form canicas
     */
    public canicas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canicaIzq = new javax.swing.JLabel();
        canicaDer = new javax.swing.JLabel();
        finishLabel = new javax.swing.JLabel();
        iniciarBtn = new javax.swing.JButton();
        cerrarBtn = new javax.swing.JButton();
        backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        canicaIzq.setIcon(new javax.swing.ImageIcon("/Users/indra/Desktop/canica izq.png")); // NOI18N
        getContentPane().add(canicaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        canicaDer.setIcon(new javax.swing.ImageIcon("/Users/indra/Desktop/canicaDerecha.png")); // NOI18N
        getContentPane().add(canicaDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        finishLabel.setFont(new java.awt.Font("Tiro Kannada", 0, 48)); // NOI18N
        finishLabel.setForeground(new java.awt.Color(255, 255, 255));
        finishLabel.setText("Meta");
        getContentPane().add(finishLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 90));

        iniciarBtn.setText("Iniciar");
        iniciarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        cerrarBtn.setText("Cerrar");
        cerrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        backgroud.setIcon(new javax.swing.ImageIcon("/Users/indra/Desktop/telon canicas.jpeg")); // NOI18N
        getContentPane().add(backgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBtnActionPerformed
        
        izq.addObserver(this);
        der.addObserver(this);
         
        Thread hIzq = new Thread(izq);
        Thread hDer = new Thread(der);
       
        hIzq.start();
        hDer.start();
        
    }//GEN-LAST:event_iniciarBtnActionPerformed

    private void cerrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBtnActionPerformed
System.exit(0);
    }//GEN-LAST:event_cerrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(canicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(canicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(canicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(canicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new canicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroud;
    private javax.swing.JLabel canicaDer;
    private javax.swing.JLabel canicaIzq;
    private javax.swing.JButton cerrarBtn;
    private javax.swing.JLabel finishLabel;
    private javax.swing.JButton iniciarBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
    canicaIzq.setLocation(200, izq.distancia);
    canicaDer.setLocation(355, der.distancia);
        }
}
